### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by 878is878** [878is878/Todo_sealion#30]
### 概要
WithTODO(ウィズトド)は、基本的なToDoリスト機能に加え、タスク達成によりトドのキャラクターを育成できるアプリです。習慣化を楽しくするためのツールとして、ユーザーのタスク管理をサポートします。

### 実装予定の機能
ユーザー登録・ログイン機能
基本的なToDoリスト機能（タスク追加、編集、削除）
「やってみる」機能（他のユーザーのタスクを自分のタスクリストに追加）
トドのキャラクター表示と育成機能（エサやり、時間帯による会話）
トドの旅機能（交流要素）
通知機能（タスクのリマインド）

### 必要なページ
- [ ] トップページ
- [ ] ログインページ
- [ ] 新規登録ページ
- [ ] タスク一覧ページ
- [ ] トド詳細ページ
- [ ] 旅トド表示ページ
- [ ] メールアドレス再設定用ページ
- [ ] パスワード再設定用ページ
- [ ] 設定ページ
- [ ] プライバシーポリシー
- [ ] 利用規約
- [ ] [開発用]トド会話追加ページ

**Comment by ky0613** [comment]
以下のようにリポジトリに紐づくprojectsが確認できないので、対応をお願いします。
[![Image from Gyazo](https://i.gyazo.com/2376bd5ac52e30c8acbd8a2bd327f8dd.png)](https://gyazo.com/2376bd5ac52e30c8acbd8a2bd327f8dd)

**Comment by 878is878** [comment]
修正しました。改めてよろしくお願いします

**Comment by ky0613** [comment]
提出ありがとうございます。
以下コメントになります。

----

- ストーリーポイントが設定されていないカードがあるので設定をお願いします。
- ストーリーポイントが5以上のものは進めていることを確認するためにも、2か3くらいの粒度に分解すると良いと思います。

**Comment by Tsuchiya2** [comment]
確認しました。
「やってみる」機能の作成が8ポイントになっていました。ポイント1,2,3になるくらい細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

---

以下、MVPリリース後でも良いかと思ったカードになります。
- ダークモード
- イラスト
- 利用規約等
- リマインド
- 他のトド
- 画像のトリミング機能
- プロフィール
- メールアドレスの変更
- パスワードリセット

※デプロイはrails new直後に行いましょう。

**Comment by 878is878** [comment]
>他のトド
表示された他のトドから「やってみる」画面にアクセス可能な仕様となっているのでこの項目は残します。

**Comment by 878is878** [comment]
デプロイ作業がうまくいかず作業の進行ができません。一先ず、issueのレビューをお願いしたいです

**Comment by 878is878** [comment]
ここで聞いて良いものかわかりませんが、デプロイに関する事柄を技術面談で質問することは可能なのでしょうか。
AWSとFly.ioの二つを試しましたが、うまくいかず停滞しています

**Comment by tmtkzk0823** [comment]
確認させていただきました。
概ね良さそうです。
LGTMです！

> ここで聞いて良いものかわかりませんが、デプロイに関する事柄を技術面談で質問することは可能なのでしょうか。
AWSとFly.ioの二つを試しましたが、うまくいかず停滞しています

上記の内容は技術面談で相談可能です。
